#!/bin/bash

# Define colors
RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"
MAGENTA="\033[35m"
CYAN="\033[36m"
RESET="\033[0m"

# Function to clear the screen and display time
display_time() {
  # Get terminal size
  rows=$(tput lines)
  cols=$(tput cols)

  # Get current time
  current_time=$(date +"%T")
  
  # Select random color
  color=$((RANDOM % 6))
  case $color in
    0) COLOR=$RED ;;
    1) COLOR=$GREEN ;;
    2) COLOR=$YELLOW ;;
    3) COLOR=$BLUE ;;
    4) COLOR=$MAGENTA ;;
    5) COLOR=$CYAN ;;
  esac

  # Calculate where to place the clock
  start_row=$((rows / 2))
  start_col=$(( (cols - ${#current_time}) / 2 ))

  # Move the cursor to the center and display time
  tput cup $start_row $start_col
  echo -e "${COLOR}${current_time}${RESET}"
}

# Infinite loop to update the time every second
while true; do
  clear
  display_time
  sleep 1
done
